CUDA_VISIBLE_DEVICES=0 python -u train_base.py \
                           --save_root "./vgg16/base/" \
                           --data_name cifar10 \
                           --epochs 1 \
                           --lr 0.0001 \
                           --optimizer Adam \
                           --print_freq 200 \
                           --num_class 10 \
                           --net_name resnet20 \
                           --test_only \
                           --net_type 'cus' \
                           --first_ch 4 \
                           --pretrained 'results/resnet18/base-c10-resnet18_cus4/model_best_8804.pth.tar' \
                           --note just-test_only